[versions]
kotlin = "1.8.21"
auto-service = "1.0.1"
kotlinpoet = "1.13.1"
compileTesting = "1.5.0"
incap = "0.3"
ksp = "1.8.21-1.0.11"

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlinx-binaryCompatibilityValidator = "org.jetbrains.kotlinx.binary-compatibility-validator:0.13.0"

[libraries]
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

dokka-gradlePlugin = "org.jetbrains.dokka:dokka-gradle-plugin:1.8.10"

auto-common = "com.google.auto:auto-common:1.2.1"

auto-service-api = { module = "com.google.auto.service:auto-service-annotations", version.ref = "auto-service" }
auto-service-compiler = { module = "com.google.auto.service:auto-service", version.ref = "auto-service" }

kotlinpoet-core = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-metadata = { module = "com.squareup:kotlinpoet-metadata", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoet" }

kotlinx-metadata = "org.jetbrains.kotlinx:kotlinx-metadata-jvm:0.6.0"

junit = "junit:junit:4.12"
assertk = "com.willowtreeapps.assertk:assertk-jvm:0.25"

compileTesting-core = { module = "com.github.tschuchortdev:kotlin-compile-testing", version.ref = "compileTesting" }
compileTesting-ksp = { module = "com.github.tschuchortdev:kotlin-compile-testing-ksp", version.ref = "compileTesting" }

moshi-oldestSupported = "com.squareup.moshi:moshi:1.8.0"
moshi-current = "com.squareup.moshi:moshi:1.14.0"

findBugs = "com.google.code.findbugs:jsr305:3.0.2"

incap-api = { module = "net.ltgt.gradle.incap:incap", version.ref = "incap" }
incap-compiler = { module = "net.ltgt.gradle.incap:incap-processor", version.ref = "incap" }

ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }

asm = "org.ow2.asm:asm:9.5"