[versions]
kotlin = "1.9.0"
auto-service = "1.1.1"
kotlinpoet = "1.14.2"
compileTesting = "1.5.0"
incap = "1.0.0"
ksp = "1.9.10-1.0.13"

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlinx-binaryCompatibilityValidator = "org.jetbrains.kotlinx.binary-compatibility-validator:0.13.2"

[libraries]
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

dokka-gradlePlugin = "org.jetbrains.dokka:dokka-gradle-plugin:1.8.20"

auto-common = "com.google.auto:auto-common:1.2.2"

auto-service-api = { module = "com.google.auto.service:auto-service-annotations", version.ref = "auto-service" }
auto-service-compiler = { module = "com.google.auto.service:auto-service", version.ref = "auto-service" }

kotlinpoet-core = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-metadata = { module = "com.squareup:kotlinpoet-metadata", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoet" }

kotlinx-metadata = "org.jetbrains.kotlinx:kotlinx-metadata-jvm:0.7.0"

junit-jupiter = "org.junit.jupiter:junit-jupiter:5.10.0"

assertk = "com.willowtreeapps.assertk:assertk-jvm:0.26.1"

compileTesting-core = { module = "com.github.tschuchortdev:kotlin-compile-testing", version.ref = "compileTesting" }
compileTesting-ksp = { module = "com.github.tschuchortdev:kotlin-compile-testing-ksp", version.ref = "compileTesting" }

moshi-oldestSupported = "com.squareup.moshi:moshi:1.8.0"
moshi-current = "com.squareup.moshi:moshi:1.15.0"

findBugs = "com.google.code.findbugs:jsr305:3.0.2"

incap-api = { module = "net.ltgt.gradle.incap:incap", version.ref = "incap" }
incap-compiler = { module = "net.ltgt.gradle.incap:incap-processor", version.ref = "incap" }

ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }

asm = "org.ow2.asm:asm:9.5"

shadow = "com.github.johnrengelman:shadow:8.1.1"
