[versions]
kotlin = "2.1.10"
auto-service = "1.1.1"
kotlinpoet = "2.0.0"
compileTesting = "0.7.0"
incap = "1.0.0"
ksp = "2.1.0-1.0.29"
moshi-oldestSupported = "1.8.0"
moshi-latest = "1.15.2"

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlinx-binaryCompatibilityValidator = "org.jetbrains.kotlinx.binary-compatibility-validator:0.17.0"

[libraries]
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-metadata = { module = "org.jetbrains.kotlin:kotlin-metadata-jvm", version.ref = "kotlin" }

sonatypePublishFix = "se.ansman.sonatype-publish-fix:gradle-plugin:1.0.0"

dokka-gradlePlugin = "org.jetbrains.dokka:dokka-gradle-plugin:2.0.0"

auto-common = "com.google.auto:auto-common:1.2.2"

auto-service-api = { module = "com.google.auto.service:auto-service-annotations", version.ref = "auto-service" }
auto-service-compiler = { module = "com.google.auto.service:auto-service", version.ref = "auto-service" }

kotlinpoet-core = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-metadata = { module = "com.squareup:kotlinpoet-metadata", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoet" }

junit-jupiter = "org.junit.jupiter:junit-jupiter:5.11.4"

assertk = "com.willowtreeapps.assertk:assertk-jvm:0.28.1"

compileTesting-core = { module = "dev.zacsweers.kctfork:core", version.ref = "compileTesting" }
compileTesting-ksp = { module = "dev.zacsweers.kctfork:ksp", version.ref = "compileTesting" }

moshi-latest = { module = "com.squareup.moshi:moshi", version.ref = "moshi-latest" }

findBugs = "com.google.code.findbugs:jsr305:3.0.2"

incap-api = { module = "net.ltgt.gradle.incap:incap", version.ref = "incap" }
incap-compiler = { module = "net.ltgt.gradle.incap:incap-processor", version.ref = "incap" }

ksp = { module = "com.google.devtools.ksp:symbol-processing", version.ref = "ksp" }
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
ksp-commonDeps = { module = "com.google.devtools.ksp:symbol-processing-common-deps", version.ref = "ksp" }
ksp-aaEmbeddable = { module = "com.google.devtools.ksp:symbol-processing-aa-embeddable", version.ref = "ksp" }

asm = "org.ow2.asm:asm:9.7.1"